### ISSUE TITLE
About void 0 & undefined.

### ISSUE THREAD

**Issue by castlerek** [elierotenberg/coding-styles#9]
Have read your article.

```
undefined

undefined must not be used, void 0 must be used instead.
// bad
if(x === undefined) {
 ...
}

// good
if(x === void 0) {
...
}
```

Is it really bad? `undefined` is a primitive data type, `void` is an operator, which always returns `undefined`. Are you serious? Can you describe the sense?

I can see the only sense with defending against fools, who may override `undefined`. The only sense... But it's also another question... If a fool is coding, then he may do many stupid things...

**Comment by elierotenberg** [comment]
Like many other rules in these coding styles, its more about pure convention than arguing: when two rules are equivalent besides bikeshedding, pick one and stick to it.
